# 在 GitHub Pages 上构建和部署 Jekyll 站点的示例工作流
名字: Deploy Jekyll with GitHub Pages dependencies preinstalled

在:
# 在针对默认分支的推送操作上运行
推送：:
分支：["主分支"]: ["main"]

允许您从“操作”选项卡手动运行此工作流。
  workflow_dispatch:

# 将 GITHUB_TOKEN 的权限设置为允许部署到 GitHub Pages
权限：:
目录：阅读: read
页数：写: write
身份令牌：写入: write

仅允许一次并发部署，跳过在运行中和最新排队运行之间的排队运行。
不过，请勿取消正在进行的运行，因为我们希望让这些生产部署完成。
并发：:
组："页面: "pages"
取消中：否: 假

工作:
# 构建任务
构建：:
运行于：ubuntu-latest: ubuntu-latest
步骤：:
- 名称：结账name: Checkout
使用：actions/checkout@v4: actions/checkout@v4
- 名称：设置页面name: Setup Pages
使用：actions/configure-pages@v5: actions/configure-pages@v5
- 名称：使用 Jekyll 构建name: Build with Jekyll
使用：actions/jekyll-build-pages@v1: actions/jekyll-build-pages@v1
和；与；跟；同；伴随；带有；具有；:
源文件：./: ./
目标路径：./_site: ./_site
- 名称：上传工件name: Upload artifact
使用：actions/upload-pages-artifact@v3: actions/upload-pages-artifact@v3

# 部署任务
部署：:
环境：:
名称：GitHub 页面: github-pages
网址：${{ 步骤部署输出的页面网址 }}: ${{ steps.deployment.outputs.page_url }}
运行于：ubuntu-latest: ubuntu-latest
需求：构建: build
步骤:
名称：部署到 GitHub Pagesname: Deploy to GitHub Pages
标识符：部署: deployment
用途；使用；用法: actions/deploy-pages@v4
